{% set name = "dashing" %}
{% set version = "0.1.0" %}

package:
  # There is a non-Python dashing package on bioconda.
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dashing-{{ version }}.tar.gz
  sha256: 2514608e0f29a775dbd1b1111561219ce83d53cfa4baa2fe4101fab84fd56f1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - blessed

test:
  imports:
    - dashing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FedericoCeratto/dashing
  summary: High-level terminal-based dashboard
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
